version: '3'

services:
  conferencertc:
    build: .
    container_name: ConferenceRTC
    volumes:
      - app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      EXTERNAL_URL: #optional https://conference.yourdomain.com
      PASSWORD: #optional password
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  app:

