version: '3'

services:
  conferencertc:
    build: .
    container_name: ConferenceRTC
    volumes:
      - config:/config
      - recordings:/recordings
    environment:
      EXTERNAL_URL: #optional https://conference.yourdomain.com
      PASSWORD: #optional password
      TTEST_TONE:  # Set to 1 to enable test tone, 0 to disable
    restart: unless-stopped
    ports:
      - "5000:5000"

volumes:
  config:
  recordings:

